site_name:  qdmtl.ca
site_url: https://qdmtl.ca
site_description: Données ouvertes et liées pour les quartiers disparus de Montréal
site_author: David Valentine

repo_name: qdmtl/qdmtl-www
repo_url: https://github.com/qdmtl/qdmtl-www
edit_uri: ./edit/main

nav:
  - Accueil: index.md
  - SPARQL: "info-sparql.md"
#  - Contribuer: "#"

theme:
  name: mkdocs
  locale: fr

extra_css:
  - css/qdmtl-style.css

plugins:
  - search:
      lang: fr

markdown_extensions:
    - toc:
        permalink: ''
    - admonition
