name: deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
      - name: Push remote
        run: |
          git config user.name "davvalent"
          git config user.email "d@ntnlv.ca"
          git remote add origin ${{ secrets.SSH_TARGET }} >> ~/.ssh/known_hosts
          git add .
          git commit -m "deploy from Github"
          git push origin main